# config.yaml
experiment_name: "emotion_recognition"
project_name: "FER_Thesis"
num_epoch: 100
learning_rate: 0.001
batch_size: 256
train_dir: "../data/train"
val_dir: "../data/test"
num_workers: 4
model_type: "resnet"  #resnet or custom