# config.yaml
experiment_name: "emotion_recognition"
project_name: "FER_Thesis"
num_epoch: 100
learning_rate: 0.001
batch_size: 64
train_dir: "/Users/abdulmalikshinkafi/FER_Thesis/data/train"
val_dir: "/Users/abdulmalikshinkafi/FER_Thesis/data/test"
num_workers: 4
